///////////////////////////////////////////////////
// This file is generated by build-interfaces.js //
///////////////////////////////////////////////////
/* eslint-disable @typescript-eslint/ban-types */
/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable @typescript-eslint/no-unsafe-assignment */
/* eslint-disable @typescript-eslint/no-unsafe-call */
/* eslint-disable @typescript-eslint/no-unsafe-member-access */
/* eslint-disable @typescript-eslint/no-unsafe-return */
/* eslint-disable @typescript-eslint/no-duplicate-type-constituents */
import { LaraJoinPoint, registerJoinpointMapper, wrapJoinPoint, unwrapJoinPoint, } from "lara-js/api/LaraJoinPoint.js";
export class Joinpoint extends LaraJoinPoint {
    /**
     * String representation of the ast.
     */
    get ast() { return wrapJoinPoint(this._javaObject.getAst()); }
    /**
     * Returns an array with the children of the node, ignoring null nodes
     */
    get children() { return wrapJoinPoint(this._javaObject.getChildren()); }
    /**
     * Retrieves all descendants of the join point
     */
    get descendants() { return wrapJoinPoint(this._javaObject.getDescendants()); }
    /**
     * The parent of this node, or undefined if it is the root node
     */
    get parent() { return wrapJoinPoint(this._javaObject.getParent()); }
    /**
     * Gets an attribute with the given name.
     */
    getValue(name) { return wrapJoinPoint(this._javaObject.getValue(unwrapJoinPoint(name))); }
    /**
     * Removes the node associated to this joinpoint from the AST
     */
    detach() { return wrapJoinPoint(this._javaObject.detach()); }
    /**
     * Inserts the given join point after this join point
     */
    insertAfter(p1) { return wrapJoinPoint(this._javaObject.insertAfter(unwrapJoinPoint(p1))); }
    /**
     * Inserts the given join point before this join point
     */
    insertBefore(p1) { return wrapJoinPoint(this._javaObject.insertBefore(unwrapJoinPoint(p1))); }
    /**
     * Replaces this node with the given node
     */
    replaceWith(p1) { return wrapJoinPoint(this._javaObject.replaceWith(unwrapJoinPoint(p1))); }
    /**
     * Overload which accepts a list of strings
     */
    replaceWithStrings(node) { return wrapJoinPoint(this._javaObject.replaceWithStrings(unwrapJoinPoint(node))); }
    /**
     * Sets the value of an attribute, returns the previous set value
     */
    setValue(name, value) { return wrapJoinPoint(this._javaObject.setValue(unwrapJoinPoint(name), unwrapJoinPoint(value))); }
}
/**
 * Any node
 */
export class Any extends Joinpoint {
}
/**
 * Top-level node
 */
export class App extends Joinpoint {
    /**
     * Adds an AST to the current program, returns the inserted join point
     */
    addAst(ast) { return wrapJoinPoint(this._javaObject.addAst(unwrapJoinPoint(ast))); }
}
const JoinpointMapper = {
    joinpoint: Joinpoint,
    any: Any,
    app: App,
};
let registered = false;
if (!registered) {
    registerJoinpointMapper(JoinpointMapper);
    registered = true;
}
//# sourceMappingURL=Joinpoints.js.map